Abort early if no posts found instead of exception
Fixes the error

    5:24:28 AM: Generating blog posts...
    5:24:28 AM: jekyll 3.3.1 | Error:  undefined method `each' for
    false:FalseClass
    5:24:28 AM: make[2]: *** [netlify_jekyll_build] Error 1
    5:24:28 AM: make[2]: Leaving directory `/opt/build/repo'
    5:24:28 AM: make[1]: *** [build] Error 2
    5:24:28 AM: make[1]: Leaving directory `/opt/build/repo'
    5:24:28 AM: make: *** [all] Error 2